<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>STAF</groupId>
    <artifactId>STAF</artifactId>
    <version>10.3.1</version>
    <packaging>pom</packaging>
    <name>STAF</name>
    <url>http://maven.apache.org</url>

    <modules>
        <module>GeneralUtilities</module>
        <module>DatabaseUtilities</module>
        <module>WebUtilities</module>
        <module>ProcessBuilderUtilities</module>
        <module>APIUtilities</module>
        <module>WiremockUtilities</module>
        <module>KafkaUtilities</module>
        <module>TDMUtilities</module>
        <module>InterFrameworkUtilities</module>
    </modules>

    <properties>
        <skipExpandCollapse>false</skipExpandCollapse>
        <logback.configurationFile>STAF-logback-fileLog.xml</logback.configurationFile>
        <toolchain-plugin-phase>validate</toolchain-plugin-phase><!--set to any value which is not phase to skip execution of toolchain plugin and set this to 'validate' to execute toolchains -->
        <java-version>17</java-version><!-- define java version here for toolchains plugin -->
        <jvm-args>--add-opens java.base/java.lang=ALL-UNNAMED</jvm-args>
        <maven-exec-plugin-version>3.5.1</maven-exec-plugin-version>
        <maven-surefire-plugin-version>3.5.3</maven-surefire-plugin-version>
        <surefire-junit47-version>3.5.3</surefire-junit47-version>
        <maven.compiler.release>${java-version}</maven.compiler.release>
        <threadCount>1</threadCount>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <selenium-version>4.9.0</selenium-version>
        <rest-assured-version>4.4.0</rest-assured-version>
        <ojdbc8-version>19.3.0.0</ojdbc8-version>
        <rest-assured-json-path-version>4.4.0</rest-assured-json-path-version>
        <json-schema-validator-version>4.4.0</json-schema-validator-version>
        <rest-assured-xml-path-version>4.4.0</rest-assured-xml-path-version>
        <java-hamcrest-version>2.0.0.0</java-hamcrest-version>
        <gherkin-version>15.0.2</gherkin-version>
        <junit-vesion>4.12</junit-vesion>
        <cucumber-java-version>1.2.5</cucumber-java-version>
        <kafka-clients-version>2.5.0</kafka-clients-version>
        <avro-version>1.8.2</avro-version>
        <kafka-avro-serializer-version>5.3.0</kafka-avro-serializer-version>
        <kafka_2.13-version>2.5.0</kafka_2.13-version>
        <cucumber-jvm-deps-version>1.0.6</cucumber-jvm-deps-version>
        <cucumber-junit-version>1.2.5</cucumber-junit-version>
        <cucumber-jvm-parallel-plugin-version>2.1.0</cucumber-jvm-parallel-plugin-version>
        <com.relevantcodes-extentreports-version>2.41.2</com.relevantcodes-extentreports-version>
        <cucumber-extentsreport-version>3.1.1</cucumber-extentsreport-version>
        <com.aventstack-extentreports-version>5.1.2</com.aventstack-extentreports-version>
        <json-version>20190722</json-version>
        <json-simple-version>1.1.1</json-simple-version>
        <jsch-version>0.1.54</jsch-version>
        <jsonassert-version>1.5.0</jsonassert-version>
        <poi-ooxml-version>3.16</poi-ooxml-version>
        <postgresql-version>42.2.18</postgresql-version>
        <cv>7.28.1</cv>
        <jakarta.annotation-api-version>3.0.0</jakarta.annotation-api-version>
        <cucumber.filter.tags>@aprm</cucumber.filter.tags>
        <maven.exec.skip>false</maven.exec.skip>
        <service.name>STAF</service.name>
        <testFailureIgnore>true</testFailureIgnore>
        <featureFilesPath>src/test/java/featureFiles</featureFilesPath>
        <runnerTemplatePath>src/test/resources/RunnerTemplate/runnertemplate.vm</runnerTemplatePath>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>io.cucumber</groupId>
                <artifactId>cucumber-bom</artifactId>
                <version>${cv}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <!-- https://mvnrepository.com/artifact/org.testng/testng -->
        <dependency>
            <groupId>org.testng</groupId>
            <artifactId>testng</artifactId>
            <version>7.11.0</version>
        </dependency>

        <dependency>
            <groupId>com.google.guava</groupId>
            <artifactId>guava</artifactId>
            <version>33.4.8-jre</version>
        </dependency>

        <dependency>
            <groupId>jakarta.annotation</groupId>
            <artifactId>jakarta.annotation-api</artifactId>
            <version>${jakarta.annotation-api-version}</version>
        </dependency>

        <dependency>
            <groupId>io.cucumber</groupId>
            <artifactId>cucumber-testng</artifactId>
        </dependency>

        <!-- https://mvnrepository.com/artifact/org.junit.jupiter/junit-jupiter-api -->
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>4.13.2</version>
        </dependency>

        <dependency>
            <groupId>io.cucumber</groupId>
            <artifactId>cucumber-java</artifactId>
        </dependency>

        <dependency>
            <groupId>io.cucumber</groupId>
            <artifactId>cucumber-junit</artifactId>
        </dependency>

        <dependency>
            <groupId>io.cucumber</groupId>
            <artifactId>cucumber-jvm</artifactId>
            <version>${cv}</version>
            <type>pom</type>
        </dependency>

        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-classic</artifactId>
            <version>1.5.18</version>
        </dependency>

        <!-- https://mvnrepository.com/artifact/com.bettercloud/vault-java-driver -->
        <dependency>
            <groupId>com.bettercloud</groupId>
            <artifactId>vault-java-driver</artifactId>
            <version>5.1.0</version>
        </dependency>

        <dependency>
            <groupId>com.github.javafaker</groupId>
            <artifactId>javafaker</artifactId>
            <version>1.0.2</version>
        </dependency>


    </dependencies>

    <repositories>
        <repository>
            <id>confluent</id>
            <url>https://packages.confluent.io/maven/</url>
        </repository>

        <repository>
            <id>STAF_repo</id>
            <name>Contains STAF Utilities</name>
            <url>https://deploy-aws.internal.vodafone.com/nexus/repository/TESTAUTO2_MAVEN</url>
        </repository>

        <repository>
            <id>amdocs_repo</id>
            <name>Contains Amdocs Repos</name>
            <url>https://deployvip.internal.vodafone.com:8080/nexus/repository</url>
        </repository>

        <repository>
            <id>TESTAUTO_SOLSTICE_MAVEN2</id>
            <name>TESTAUTO_SOLSTICE_MAVEN2</name>
            <url>https://deployvip.internal.vodafone.com:8080/nexus/repository/TESTAUTO_SOLSTICE_MAVEN2</url>
        </repository>

        <repository>
            <id>public_repo</id>
            <name>Nexus as proxy for all Maven Repos</name>
            <url>https://deployvip.internal.vodafone.com:8080/nexus/repository/MAVEN-PUBLIC_group</url>
        </repository>
    </repositories>

    <build>
        <plugins>
            <plugin>
                     <groupId>org.sonarsource.scanner.maven</groupId>
                     <artifactId>sonar-maven-plugin</artifactId>
                     <version>5.5.0.6356</version>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.14.0</version>
                <configuration>
                    <fork>true</fork>
                    <compilerArgs>
                        <arg>-J--add-opens=jdk.compiler/com.sun.tools.javac.code=ALL-UNNAMED</arg>
                        <arg>-J--add-opens=jdk.compiler/com.sun.tools.javac.comp=ALL-UNNAMED</arg>
                        <arg>-J--add-opens=jdk.compiler/com.sun.tools.javac.file=ALL-UNNAMED</arg>
                        <arg>-J--add-opens=jdk.compiler/com.sun.tools.javac.main=ALL-UNNAMED</arg>
                        <arg>-J--add-opens=jdk.compiler/com.sun.tools.javac.model=ALL-UNNAMED</arg>
                        <arg>-J--add-opens=jdk.compiler/com.sun.tools.javac.parser=ALL-UNNAMED</arg>
                        <arg>-J--add-opens=jdk.compiler/com.sun.tools.javac.processing=ALL-UNNAMED</arg>
                        <arg>-J--add-opens=jdk.compiler/com.sun.tools.javac.tree=ALL-UNNAMED</arg>
                        <arg>-J--add-opens=jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED</arg>
                        <arg>-J--add-opens=jdk.compiler/com.sun.tools.javac.jvm=ALL-UNNAMED</arg>
                    </compilerArgs>
                    <annotationProcessorPaths>
                        <path>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                            <version>1.18.38</version>
                        </path>
                    </annotationProcessorPaths>
                    <encoding>${project.build.sourceEncoding}</encoding>
                </configuration>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <version>3.4.2</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>test-jar</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <finalName>ProjectJARs/project</finalName>
                </configuration>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-toolchains-plugin</artifactId>
                <version>3.2.0</version>
                <configuration>
                    <toolchains>
                        <jdk>
                            <version>${java-version}</version>
                        </jdk>
                    </toolchains>
                </configuration>
                <executions>
                    <execution>
                        <phase>${toolchain-plugin-phase}</phase>
                        <goals>
                            <goal>toolchain</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-javadoc-plugin</artifactId>
                <version>3.11.3</version>
                <configuration>
                    <groups>
                        <group>
                            <title>APIUtilities</title>
                            <packages>apiutilities*:constants*:soapapiutilities*</packages>
                        </group>
                        <group>
                            <title>DatabaseUtilities</title>
                            <packages>databaseutilities*</packages>
                        </group>
                        <group>
                            <title>GeneralUtilities</title>
                            <packages>aws*:com.solstice.staf*:generalutilities*:integrationreporting*:reporting*
                            </packages>
                        </group>

                        <group>
                            <title>InterFrameworkUtilities</title>
                            <packages>com.solstice.staf.interframework.integrationtests*</packages>
                        </group>
                        <group>
                            <title>KafkaUtilities</title>
                            <packages>kafkautilities*:staf.kafkautilities*</packages>
                        </group>
                        <group>
                            <title>ProcessBuilderUtilities</title>
                            <packages>processbuilderutilities*</packages>
                        </group>
                        <group>
                            <title>TdmUtilitiess</title>
                            <packages>tdmutilities*</packages>
                        </group>
                        <group>
                            <title>WebUtilities</title>
                            <packages>webutilities*</packages>
                        </group>
                        <group>
                            <title>WiremockUtilities</title>
                            <packages>wiremockutilities*</packages>
                        </group>

                    </groups>
                </configuration>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-scm-publish-plugin</artifactId>
                <version>3.3.0</version>
                <configuration>
                    <pubScmUrl>scm:git:https://github.vodafone.com/VFDE-Solstice-TestAutomation/javadocs.git</pubScmUrl>
                    <scmBranch>main</scmBranch>
                    <content>${project.build.directory}/site/apidocs</content>
                    <skipDeletedFiles>true</skipDeletedFiles>
                </configuration>
            </plugin>
        </plugins>
    </build>

    <profiles>
        <profile>
            <id>featuresParallel</id>
            <activation>
                <activeByDefault>true</activeByDefault>
            </activation>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-surefire-plugin</artifactId>
                        <version>${maven-surefire-plugin-version}</version>
                        <dependencies>
                            <dependency>
                                <groupId>org.apache.maven.surefire</groupId>
                                <artifactId>surefire-junit47</artifactId>
                                <version>${surefire-junit47-version}</version>
                            </dependency>
                        </dependencies>
                        <configuration>
                            <argLine>${jvm-args} -Dfile.encoding=${project.build.sourceEncoding}</argLine>
                            <systemPropertyVariables>
                                <logback.configurationFile>${logback.configurationFile}</logback.configurationFile>
                                <cucumber.publish.quiet>true</cucumber.publish.quiet>
                                <cucumber.ansi-colors.disabled>false</cucumber.ansi-colors.disabled>
                            </systemPropertyVariables>
                            <parallel>methods</parallel>
                            <threadCount>${threadCount}</threadCount>
                            <testFailureIgnore>${testFailureIgnore}</testFailureIgnore>
                            <perCoreThreadCount>false</perCoreThreadCount>
                            <includes>
                                <include>**/TestRunner*.class</include>
                            </includes>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>
        <profile>
            <id>scenariosParallel</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-surefire-plugin</artifactId>
                        <version>${maven-surefire-plugin-version}</version>
                        <configuration>
                            <argLine>${jvm-args} -Dfile.encoding=${project.build.sourceEncoding}</argLine>
                            <systemPropertyVariables>
                                <logback.configurationFile>${logback.configurationFile}</logback.configurationFile>
                                <cucumber.publish.quiet>true</cucumber.publish.quiet>
                                <cucumber.ansi-colors.disabled>false</cucumber.ansi-colors.disabled>
                            </systemPropertyVariables>
                            <properties>
                                <property>
                                    <name>dataproviderthreadcount</name>
                                    <value>${threadCount}</value>
                                </property>
                            </properties>
                            <testFailureIgnore>${testFailureIgnore}</testFailureIgnore>
                            <includes>
                                <include>**/TestNG*.class</include>
                            </includes>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>



        <profile>
            <id>forking</id>
            <activation>
                <property>
                    <name>forkCount</name>
                </property>
            </activation>
            <build>
                <plugins>
                    <plugin>
                        <groupId>com.github.temyers</groupId>
                        <artifactId>cucumber-jvm-parallel-plugin</artifactId>
                        <version>5.0.0</version>
                        <executions>
                            <execution>
                                <id>generateRunners</id>
                                <phase>validate</phase>
                                <goals>
                                    <goal>generateRunners</goal>
                                </goals>
                                <configuration>
                                    <glue>
                                        <package>stepDefinitions</package>
                                    </glue>
                                    <plugins>
                                        <plugin>
                                            <name>com.aventstack.extentreports.cucumber.adapter.ExtentCucumberAdapter
                                            </name>
                                            <extension>html</extension>
                                        </plugin>
                                        <plugin>
                                            <name>formatter.ExecutionReport</name>
                                            <noOutput>true</noOutput>
                                        </plugin>
                                    </plugins>
                                    <featuresDirectory>${featureFilesPath}</featuresDirectory>
                                    <cucumberOutputDir>target</cucumberOutputDir>
                                    <format>json,html</format>
                                    <tags>
                                        <tag>${cucumber.filter.tags}</tag>
                                    </tags>
                                    <customVmTemplate>${runnerTemplatePath}</customVmTemplate>
                                    <parallelScheme>FEATURE</parallelScheme>
                                    <namingScheme>simple</namingScheme>
                                    <namingPattern>Parallel{c}IT</namingPattern>
                                    <useTestNG>false</useTestNG>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-surefire-plugin</artifactId>
                        <version>${maven-surefire-plugin-version}</version>
                        <dependencies>
                            <dependency>
                                <groupId>org.apache.maven.surefire</groupId>
                                <artifactId>surefire-junit47</artifactId>
                                <version>${surefire-junit47-version}</version>
                            </dependency>
                        </dependencies>
                        <configuration>
                            <systemPropertyVariables>
                                <logback.configurationFile>${logback.configurationFile}</logback.configurationFile>
                            </systemPropertyVariables>
                            <argLine>${jvm-args} -Dfile.encoding=${project.build.sourceEncoding}</argLine>
                            <forkCount>${forkCount}</forkCount>
                            <reuseForks>true</reuseForks>
                            <testFailureIgnore>${testFailureIgnore}</testFailureIgnore>
                            <useUnlimitedThreads>true</useUnlimitedThreads>
                            <includes>
                                <include>**/Parallel*IT.class</include>
                            </includes>
                        </configuration>
                    </plugin>

                    <plugin>
                        <groupId>org.codehaus.mojo</groupId>
                        <artifactId>exec-maven-plugin</artifactId>
                        <version>${maven-exec-plugin-version}</version>
                        <configuration>
                            <systemProperties>
                                <systemProperty>
                                    <key>file.encoding</key>
                                    <value>${project.build.sourceEncoding}</value>
                                </systemProperty>
                            </systemProperties>
                        </configuration>
                        <executions>
                            <execution>
                                <id>JsonMerger</id>
                                <phase>test</phase>
                                <goals>
                                    <goal>exec</goal>
                                </goals>
                                <configuration>
                                    <executable>java</executable>
                                    <longClasspath>true</longClasspath>
                                    <arguments>
                                        <argument>-DskipExpandCollapse=${skipExpandCollapse}</argument>
                                        <argument>-Dlogback.configurationFile=${logback.configurationFile}</argument>
                                        <argument>-classpath</argument>
                                        <classpath/>
                                        <argument>generalutilities.JsonMerger</argument>
                                    </arguments>
                                    <skip>${maven.exec.skip}</skip>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>

        <profile>
            <id>dd-civisibility</id>
            <activation>
                <activeByDefault>false</activeByDefault>
            </activation>
            <properties>
                <dd.java.agent.arg>
                    -javaagent:${settings.localRepository}/com/datadoghq/dd-java-agent/0.110.0/dd-java-agent-0.110.0.jar
                    -Ddd.service=${service.name} -Ddd.civisibility.enabled=true
                </dd.java.agent.arg>
            </properties>
            <dependencies>
                <dependency>
                    <groupId>com.datadoghq</groupId>
                    <artifactId>dd-java-agent</artifactId>
                    <version>1.53.0</version>
                    <scope>provided</scope>
                </dependency>
            </dependencies>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-surefire-plugin</artifactId>
                        <version>${maven-surefire-plugin-version}</version>
                        <dependencies>
                            <dependency>
                                <groupId>org.apache.maven.surefire</groupId>
                                <artifactId>surefire-junit47</artifactId>
                                <version>${surefire-junit47-version}</version>
                            </dependency>
                        </dependencies>
                        <configuration>
                            <includes>
                                <include>**/*TestRunner.java</include>
                            </includes>
                            <argLine>${dd.java.agent.arg} -Dfile.encoding=${project.build.sourceEncoding}</argLine>
                            <classesDirectory>${project.build.outputDirectory}</classesDirectory>
                            <systemPropertyVariables>
                                <logback.configurationFile>${logback.configurationFile}</logback.configurationFile>
                                <cucumber.publish.quiet>true</cucumber.publish.quiet>
                                <cucumber.ansi-colors.disabled>false</cucumber.ansi-colors.disabled>
                            </systemPropertyVariables>
                            <testFailureIgnore>${testFailureIgnore}</testFailureIgnore>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>
</project>
