<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <artifactId>STAF</artifactId>
        <groupId>STAF</groupId>
        <version>10.3.1</version>
    </parent>

    <artifactId>InterFrameworkUtilities</artifactId>
    <name>InterFrameworkUtilities</name>
    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <dependencies>

        <dependency>
            <groupId>STAF</groupId>
            <artifactId>GeneralUtilities</artifactId>
            <version>${project.parent.version}</version>
        </dependency>

        <dependency>
            <groupId>STAF</groupId>
            <artifactId>GeneralUtilities</artifactId>
            <classifier>tests</classifier>
            <version>${project.parent.version}</version>
        </dependency>

        <dependency>
            <groupId>de.kabeldeutschland.wss.testsuitedatareport</groupId>
            <artifactId>TestSuiteDataReportClient</artifactId>
            <version>2350.2024.03.00.25-shaded</version>
            <classifier>shaded</classifier>
        </dependency>

    </dependencies>

</project>
