#This workflow is used to create STAF release version artifact from main branch and upload to nexus

name: Artifact Creation - release version
run-name: Artifact Creation - release version

on:
  workflow_dispatch:

    inputs:
      versionCategory:
        description: 'Choose your version category'
        required: true
        type: choice
        options:
          - 'Major'
          - 'Minor'
          - 'Patch'
        default: 'Patch'

jobs:
  ArtifactCreation-releaseVersion:
    runs-on:
      group: cicdhub-runners
      labels: self-hosted-standard

    steps:
      - name: Creating New Artifact Version Number
        id: versionNumber
        uses: VFDE-Solstice-TestAutomation/staf-actions/artifact-version-number-action@main
        with:
            artifactId: 'STAF'
            versionCategory: ${{ inputs.versionCategory }}
            STAF_Nexus_UserName: ${{ secrets.STAF_REPO_USERNAME }}
            STAF_Nexus_Password: ${{ secrets.STAF_REPO_PASSWORD }}
    
      - name: Generate Token
        id: generate_token
        uses: VFDE-SOL/mirror-action-tibdex-github-app-token@v1.8.0
        with:
          app_id:  ${{ secrets.STAF_APP_ID }}   
          private_key: ${{ secrets.STAF_PRIVATE_KEY }} 
          
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ steps.generate_token.outputs.token }}

      - name: STAF runner set up
        uses: VFDE-Solstice-TestAutomation/staf-actions/runner-setup-action@main
        with:
          nexus-certificate: ${{ vars.NEXUS_CERTIFICATE }}
          servers: |
            [{
              "id": "STAF_repo",
              "username": "${{ secrets.STAF_REPO_USERNAME }}",
              "password": "${{ secrets.STAF_REPO_PASSWORD }}"
            },
            {
              "id": "TESTAUTO_SOLSTICE_MAVEN2",
              "username": "${{ secrets.NEXUS_REPO_USERNAME }}",
              "password": "${{ secrets.NEXUS_REPO_PASSWORD }}"
            },
            {
              "id": "amdocs_repo",
              "username": "${{ secrets.AMDOCS_REPO_USERNAME }}",
              "password": "${{ secrets.AMDOCS_REPO_PASSWORD }}"
            },
            {
              "id": "public_repo",
              "username": "${{ secrets.PUBLIC_REPO_USERNAME }}",
              "password": "${{ secrets.PUBLIC_REPO_PASSWORD }}"
            }]
            
      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2/repository/*/*
            !~/.m2/repository/STAF/STAF
          key: ${{ runner.os }}-maven-
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Sonarqube analysis
        uses: VFDE-Solstice-TestAutomation/staf-actions/sonarqube-scan-action@main
        with:
          sonarHostUrl: ${{ vars.SONAR_HOST_URL }}
          sonarToken: ${{ secrets.SONAR_TOKEN }}
          projectKey: ${{ vars.PROJECT_KEY }}
          projectName: ${{ vars.PROJECT_NAME }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          runScanOn: 'main'
          bypassScanResult: 'true' # Specify 'true' to bypass scan results. Default is 'false'.
            
      - name: Create Artifact
        run: |
          git config --global user.email "staf-action-bot@vodafone.com"
          git config --global user.name "staf-action-bot"
          git checkout main
          git pull origin main
          git status
          mvn versions:set -DnewVersion=${{ steps.versionNumber.outputs.newVersionNumber }}
          mvn clean install -Dmaven.exec.skip=true -DskipTests -Dmaven.wagon.http.ssl.insecure=true -T 10
          
      - name: Upload Artifact
        env:
          currentVersionNo: ${{ steps.versionNumber.outputs.newVersionNumber }}
          groupId: "STAF"
          repositoryId: "STAF_repo"
          url: "https://vf-aws-access.deliveryzone.vodafone.com/nexus/repository/TESTAUTO2_MAVEN/"
          
        run: |
          mvn deploy:deploy-file -DgroupId=${groupId} -DartifactId=STAF -DgeneratePom=false -Dversion=${currentVersionNo} -Dmaven.wagon.http.ssl.insecure=true -Dpackaging=jar -DrepositoryId=${repositoryId} -Durl=${url} -Dclassifier=tests -Dfile=target/ProjectJARs/project-tests.jar -DpomFile=pom.xml
          mvn deploy:deploy-file -DgroupId=${groupId} -DartifactId=APIUtilities -DgeneratePom=false -Dversion=${currentVersionNo} -Dmaven.wagon.http.ssl.insecure=true -Dpackaging=jar -DrepositoryId=${repositoryId} -Durl=${url} -Dfile=APIUtilities/target/ProjectJARs/project.jar -DpomFile=APIUtilities/pom.xml -Dfiles=APIUtilities/target/ProjectJARs/project-tests.jar -Dclassifiers=tests -Dtypes=jar
          mvn deploy:deploy-file -DgroupId=${groupId} -DartifactId=DatabaseUtilities -DgeneratePom=false -Dversion=${currentVersionNo} -Dmaven.wagon.http.ssl.insecure=true -Dpackaging=jar -DrepositoryId=${repositoryId} -Durl=${url} -Dfile=DatabaseUtilities/target/ProjectJARs/project.jar -DpomFile=DatabaseUtilities/pom.xml -Dfiles=DatabaseUtilities/target/ProjectJARs/project-tests.jar -Dclassifiers=tests -Dtypes=jar
          mvn deploy:deploy-file -DgroupId=${groupId} -DartifactId=GeneralUtilities -DgeneratePom=false -Dversion=${currentVersionNo} -Dmaven.wagon.http.ssl.insecure=true -Dpackaging=jar -DrepositoryId=${repositoryId} -Durl=${url} -Dfile=GeneralUtilities/target/ProjectJARs/project.jar -DpomFile=GeneralUtilities/pom.xml -Dfiles=GeneralUtilities/target/ProjectJARs/project-tests.jar -Dclassifiers=tests -Dtypes=jar
          mvn deploy:deploy-file -DgroupId=${groupId} -DartifactId=KafkaUtilities -DgeneratePom=false -Dversion=${currentVersionNo} -Dmaven.wagon.http.ssl.insecure=true -Dpackaging=jar -DrepositoryId=${repositoryId} -Durl=${url} -Dfile=KafkaUtilities/target/ProjectJARs/project.jar -DpomFile=KafkaUtilities/pom.xml -Dfiles=KafkaUtilities/target/ProjectJARs/project-tests.jar -Dclassifiers=tests -Dtypes=jar
          mvn deploy:deploy-file -DgroupId=${groupId} -DartifactId=ProcessBuilderUtilities -DgeneratePom=false -Dversion=${currentVersionNo} -Dmaven.wagon.http.ssl.insecure=true -Dpackaging=jar -DrepositoryId=${repositoryId} -Durl=${url} -Dfile=ProcessBuilderUtilities/target/ProjectJARs/project.jar -DpomFile=ProcessBuilderUtilities/pom.xml -Dfiles=ProcessBuilderUtilities/target/ProjectJARs/project-tests.jar -Dclassifiers=tests -Dtypes=jar
          mvn deploy:deploy-file -DgroupId=${groupId} -DartifactId=TDMUtilities -DgeneratePom=false -Dversion=${currentVersionNo} -Dmaven.wagon.http.ssl.insecure=true -Dpackaging=jar -DrepositoryId=${repositoryId} -Durl=${url} -Dfile=TDMUtilities/target/ProjectJARs/project.jar -DpomFile=TDMUtilities/pom.xml -Dfiles=TDMUtilities/target/ProjectJARs/project-tests.jar -Dclassifiers=tests -Dtypes=jar
          mvn deploy:deploy-file -DgroupId=${groupId} -DartifactId=WebUtilities -DgeneratePom=false -Dversion=${currentVersionNo} -Dmaven.wagon.http.ssl.insecure=true -Dpackaging=jar -DrepositoryId=${repositoryId} -Durl=${url} -Dfile=WebUtilities/target/ProjectJARs/project.jar -DpomFile=WebUtilities/pom.xml -Dfiles=WebUtilities/target/ProjectJARs/project-tests.jar -Dclassifiers=tests -Dtypes=jar
          mvn deploy:deploy-file -DgroupId=${groupId} -DartifactId=WiremockUtilities -DgeneratePom=false -Dversion=${currentVersionNo} -Dmaven.wagon.http.ssl.insecure=true -Dpackaging=jar -DrepositoryId=${repositoryId} -Durl=${url} -Dfile=WiremockUtilities/target/ProjectJARs/project.jar -DpomFile=WiremockUtilities/pom.xml -Dfiles=WiremockUtilities/target/ProjectJARs/project-tests.jar -Dclassifiers=tests -Dtypes=jar
          mvn deploy:deploy-file -DgroupId=${groupId} -DartifactId=InterFrameworkUtilities -DgeneratePom=false -Dversion=${currentVersionNo} -Dmaven.wagon.http.ssl.insecure=true -Dpackaging=jar -DrepositoryId=${repositoryId} -Durl=${url} -Dfile=InterFrameworkUtilities/target/ProjectJARs/project.jar -DpomFile=InterFrameworkUtilities/pom.xml -Dfiles=InterFrameworkUtilities/target/ProjectJARs/project-tests.jar -Dclassifiers=tests -Dtypes=jar
         
      - name: Change version in source code 
        run: |          
          git commit -am "added new version ${{ steps.versionNumber.outputs.newVersionNumber }}"
          git push -u origin main -f
          git tag ${{ steps.versionNumber.outputs.newVersionNumber }}
          git push --tags
